PROGRAM DEMO;
  
  USES TURTLEGRAPICS, APPLESTUFF;
  VAR ANGLE, DISTANCE: INTEGER;
  
  PROCEDURE CRAWL;
  BEGIN
    MOVE (2 * DISTANCE);
    TURN (ANGLE)
  END;
  
  BEGIN
    ANGLE := 0;
    REPEAT
      INITTURTLE;
      PENCOLOR (WHITE);
      FOR DISTANCE := 1 TO 99 DO CRAWL;
      ANGLE := ANGLE + 5
    UNTIL KEYPRESS;
    TEXTMODE
  END.
